"""Build the GW1 minutes overlay from the research legs.

Every entry carries a written reason (CLAUDE.md rule 4: models propose, the manager
disposes, and every deviation is written down). duration_gws scopes the news: the
World Cup fitness deficit is a GW1-3 effect, not an 8-GW one — pricing a transient
as permanent is the overlay-horizon defect the backtest already paid for once.
"""
import json
import unicodedata
from pathlib import Path

ROOT = Path(r"C:\Users\pau_8\Documents\fpl-claude")
bs = json.loads((ROOT / "db" / "raw" / "2026-07-25" / "bootstrap.json").read_text(encoding="utf-8"))
short = {t["id"]: t["short_name"] for t in bs["teams"]}


def norm(s):
    return "".join(
        c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c)
    ).lower()


by_name = {}
for e in bs["elements"]:
    by_name.setdefault((norm(e["web_name"]), short[e["team"]]), []).append(e)

# (web_name, club): (start_share, duration_gws, reason)
OVERLAYS = {
    # ---------- WORLD CUP LATE RETURNERS: fade GW1-3, clean thereafter ----------
    ("rogers", "CHE"): (0.45, 3, "Morgan Rogers (Chelsea MID, PS7.5, 34.8% owned) — the single biggest fade on the board, on THREE independent counts. (1) England reached the WC semi-final (lost 1-2 to Argentina 15 Jul) then played the 3rd-place play-off on 18 Jul, so mandated rest ends ~10-12 Aug and he arrives at the deadline with ~10 days of club training and zero friendlies. (2) He is a BRAND-NEW signing (PS117m from Villa, joined 2026-07-21, four days before this snapshot) into Xabi Alonso's new Chelsea, so he has neither pre-season nor system familiarity. (3) He takes NO Chelsea set pieces — Palmer is pens #1, Enzo #2, Estevao #3 — having been Villa's dead-ball man, and he queues behind Palmer/Joao Pedro/Estevao for the No.10 role. 34.8% of the game owns him; we own none of him for GW1. Sources: research/2026-27/fitness-returners.md Table 2, transfers.md sec 1."),
    ("guehi", "MCI"): (0.5, 3, "Marc Guehi (Man City DEF, PS6.0, 25.3% owned) — England semi-finalist, so the ~10-day pre-season applies. REVISED UP from an initial 0.42 after the team-landscape leg: it rates Guehi the CORRECT City defender to own, because Maresca's box midfield inverts the full-backs and it is the centre-backs, not the full-backs, who hold stable defensive minutes. The residual risk is fitness and a new manager's first XI, not his place in the pecking order. Our raw model separately hands him his Crystal Palace start share (37 starts as an undroppable captain) and applies it to a title-contender back line — the 'confidently wrong' class from minutes-blindspots.md — so the overlay is doing double duty here."),
    ("o'reilly", "MCI"): (0.38, 3, "Nico O'Reilly (Man City DEF, PS6.5, 24.8% owned) — the sharpest DISAGREEMENT between our two research legs, resolved against the crowd. Fitness says England semi-finalist, ~10 days of pre-season. The team-landscape leg says something worse and more durable: Maresca's box midfield INVERTS the full-backs, so 24.8% of the game is paying PS6.5 for attacking returns the system does not produce. That is a structural mispricing, not a transient one — the only reason duration is 3 rather than 8 is that we will re-read it once City have actually played. Faded HARDER than Guehi, inverting the model's ordering of the two."),
    ("rice", "ARS"): (0.52, 3, "Declan Rice (Arsenal MID, PS7.5, 22.5% owned) — England semi-finalist. Arsenal are the WORST-hit club in the league for World Cup load (Raya, Rice, Saka, Eze, Madueke, Zubimendi, Merino all returning ~10-12 Aug, with Saliba injured in the semi and out 4-5 months). Rice is Arsenal's corner and direct-free-kick #1 so the ceiling is real, but a GW1 start on ten days' training is not something to pay PS7.5 for. Re-read after the Community Shield (ARS v MCI, 16 Aug)."),
    ("saka", "ARS"): (0.5, 3, "Bukayo Saka (Arsenal MID, PS9.5, 11.2% owned) — England semi-finalist and EXPLICITLY reported unavailable for Arsenal's 1 Aug friendly at Girona. Arsenal's penalty #1, so genuinely elite when fit and sharp, but PS9.5 buys us nothing in the weeks he is being reintegrated. The GW1 fixture (COV at home, FDR2) is the softest on the slate, which is exactly why the crowd will reach for him — the fixture is only worth having if he starts and lasts."),
    ("enzo", "CHE"): (0.5, 3, "Enzo Fernandez (Chelsea MID, PS7.0, 5.1% owned) — went to the very END of the World Cup as an Argentina runner-up and scored their 85' equaliser against England, so he is in the deepest-fatigue cohort (rest to ~10-12 Aug). Chelsea also have a new manager (Xabi Alonso) trialling both a 4-2-3-1 and a back three. Our raw model rates him top-10 in the game on last season's rates; the fade is fitness and system, not talent."),
    ("senesi", "TOT"): (0.5, 3, "Marcos Senesi (Spurs DEF, PS6.0, 12.7% owned) — Argentina runner-up (played to 19 Jul) AND a summer move to a new club under De Zerbi, who plays a 3-4-3. He should ultimately be one of the three centre-backs, but arriving with ~10 days of training into a brand-new back-three system is a GW1 minutes risk the price does not reflect."),
    ("pedro porro", "TOT"): (0.5, 3, "Pedro Porro (Spurs DEF, PS5.5, 23.9% owned) — Spain WORLD CHAMPION, played to the 19 Jul final, rest to ~10-12 Aug. De Zerbi's 3-4-3 makes the right wing-back role genuinely attacking and Porro is the natural fit, which is why 23.9% own him — but the fixture-adjusted case depends on him starting GW1, and he will have had under two weeks of training."),
    ("konsa", "AVL"): (0.5, 3, "Ezri Konsa (Villa DEF, PS4.5, 18.4% owned) — England semi-finalist; absent from Villa's 21 Jul friendly along with the rest of their WC quartet. An 18%-owned PS4.5 enabler whose whole value proposition is that he plays every minute; ten days of pre-season undermines precisely that."),
    ("watkins", "AVL"): (0.55, 3, "Ollie Watkins (Villa FWD, PS8.0, 13.1% owned) — England semi-finalist, absent from Villa's pre-season friendlies. Reported as only a 'slight doubt', which is why the fade is mild rather than severe — but a PS8.0 forward with no pre-season minutes is a poor GW1 bet when fit alternatives exist at the same price."),
    ("cherki", "MCI"): (0.45, 3, "Rayan Cherki (Man City MID, PS7.5, 10.2% owned) — France third-place play-off (18 Jul), so the deepest cohort, plus a new City manager. He was already a rotation risk under Guardiola; Maresca has given no indication he is nailed."),
    ("mateta", "CRY"): (0.5, 3, "Jean-Philippe Mateta (Palace FWD, PS6.5, 7.7% owned) — France third-place play-off; absent from Palace's 21 Jul friendly, where a fully second-string XI played (Nketiah 2 goals, Matheus Franca hat-trick). Palace ALSO have a new manager (Pierre Sage) whose system is unproven, so the priors are doubly unreliable."),
    ("anderson", "MCI"): (0.6, 3, "Elliot Anderson (Man City MID, PS6.5, 12.5% owned) — England semi-finalist, so the same ~10-day pre-season as the rest. Faded LESS than his City team-mates because the role signal is unusually strong: he is the PS116m British-record signing bought explicitly to be central to Maresca's midfield 'from the moment competitive football returns'. Fitness risk yes; selection risk no."),
    ("spence", "TOT"): (0.5, 3, "Djed Spence (Spurs DEF, PS4.5, 10.5% owned) — England semi-finalist. De Zerbi's 3-4-3 wing-back role is a real FPL opportunity at PS4.5, but he returns ~10-12 Aug into a new system and competes with Robertson and Porro for the two wing-back slots."),
    ("diop", "IPS"): (0.6, 3, "Issa Diop (Ipswich DEF, PS4.0, 21.4% owned) — Morocco quarter-finalist (out 10-11 Jul), so ~18-20 days back rather than ten: a MODERATE fade, not a severe one. He is the game's most-owned budget defender at a promoted club under a new manager (Gary O'Neil, back five likely). Our model is 96% blind on Ipswich, so this number is research-derived, not model-derived."),
    ("james", "CHE"): (0.45, 3, "Reece James (Chelsea DEF, PS5.5, 8.1% owned) — England semi-finalist with a long chronic-injury history, returning ~10-12 Aug into Xabi Alonso's new system. The fitness deficit compounds an already poor durability base rate."),
    ("gusto", "CHE"): (0.5, 3, "Malo Gusto (Chelsea DEF, France 3rd-place play-off) — deepest-cohort return, new manager, and direct competition with Reece James for the right-sided slot."),

    # ---------- THE FRESH: raise or confirm ----------
    ("raya", "ARS"): (0.92, 8, "David Raya (Arsenal GKP, PS6.0, 29.8% owned) — the most valuable single correction in this overlay. He is a World Cup CHAMPION with Spain who played ZERO minutes across the entire tournament (Unai Simon started every game): a champion by medal and a spectator by workload. The market's 'finalist = fatigued' heuristic is a FALSE POSITIVE here, and he is simultaneously Arsenal's nailed No.1 and the freshest premium keeper in the game. Arsenal's GW1 is Coventry at home, the softest fixture on the opening slate (FDR 2 v 5, the largest gap). Raised, not faded, against a club-wide Arsenal fade. Source: fitness-returners.md buy-low list #2."),
    ("szoboszlai", "LIV"): (0.85, 8, "Dominik Szoboszlai (Liverpool MID, PS7.0, 40.9% owned) — Hungary did not go deep; he is in the confirmed low-risk group and back in full training. Liverpool are the LEAST World-Cup-damaged big club (only Mac Allister went deep) and simultaneously own the best 8-GW fixture run in the league (summed FDR 22, and 10 across GW1-4). That convergence of fitness and fixtures is the central buy thesis of this build. CAVEAT recorded: the FPL API lists Isak as penalty #1 while FFScout says Szoboszlai — the sources conflict and neither is currently trustworthy, so no penalty premium is assumed for him."),
    ("isak", "LIV"): (0.78, 8, "Alexander Isak (Liverpool FWD, PS9.0, 12.7% owned) — Sweden exited at the round of 32 (28 Jun-3 Jul), he rejoined Liverpool the weekend of 25 Jul and is expected to feature v Wrexham (30 Jul) and Leeds (2 Aug): effectively a full three-week build-up. Held BELOW a nailed 0.85 for one honest reason — last season he managed only 694 Premier League minutes, missing 22 games to a fibula fracture and ankle surgery, and Liverpool's backup route (Ekitike) is out with a ruptured Achilles until 2027, so there is no hedge. Durability is priced; availability is not a GW1 concern."),
    ("wirtz", "LIV"): (0.8, 8, "Florian Wirtz (Liverpool MID, PS7.5, 12.2% owned) — Germany exited at the round of 32; confirmed back in Liverpool training. Iraola's 4-2-3-1 puts him in the No.10 role behind Isak. Fit, in the best fixture run in the league, and only 12.2% owned."),
    ("gakpo", "LIV"): (0.7, 8, "Cody Gakpo (Liverpool MID, PS7.0, 3.8% owned) — Netherlands exited at the round of 32, so fully rested and in training. Held at 0.7 rather than higher: Iraola's front line is genuinely contested (Wirtz, Munoz, Gakpo, Salah gone) and the new manager has no track record with this squad."),
    ("gyokeres", "ARS"): (0.78, 8, "Viktor Gyokeres (Arsenal FWD, PS7.5, 14.7% owned) — Sweden exited at the round of 32 and he is EXPLICITLY reported as available for the start of Arsenal pre-season. The structural point: in a squad where Saka, Rice, Eze, Madueke, Raya, Zubimendi and Merino only return ~10 Aug, the FIT Arsenal attackers get the early minutes by default. He is also Arsenal's penalty #2 behind Saka — and if Saka is being reintegrated, that matters. Arsenal host Coventry (FDR2) in GW1."),
    ("palmer", "CHE"): (0.8, 8, "Cole Palmer (Chelsea MID, PS9.5, 13.4% owned) — the England snub is a GIFT. He was left out of the World Cup squad on form/fitness grounds and therefore gets a complete pre-season while every rival premium attacker is jet-lagged. He is Chelsea's penalty #1 and set-piece hub. The offsetting risk is real and deliberately priced at 0.8 rather than 0.88: a chronic groin/muscle history that cost him 15 matches Aug-Nov last season. Availability edge for GW1-4 is large; season-long durability is not assumed."),
    ("gibbs-white", "NFO"): (0.85, 8, "Morgan Gibbs-White (Forest MID, PS8.0, 13.2% owned) — no tournament, and he STARTED AND ASSISTED in Oliver Glasner's first friendly (2-0 v Notts County, 18 Jul). That is the clearest concrete fitness signal of any PS8.0 midfielder in the game. Offsetting risk written down: Glasner is a brand-new manager running a 3-4-2-1, so Forest's minutes priors are unreliable — but Gibbs-White is the one Forest attacker whose role is not in doubt, and he is Forest's direct-free-kick taker."),
    ("b.fernandes", "MUN"): (0.88, 8, "Bruno Fernandes (Man Utd MID, PS12.0, 47.9% owned) — confirmed in the low-World-Cup-risk group (Portugal did not go deep) and fit through pre-season under Carrick, who is a RETURNING manager, so United's priors are among the few still trustworthy. He is United's penalty #1 and set-piece hub. United also have the best opening PAIR of fixtures in the league: Hull away (FDR2) then Ipswich at home (FDR2), both against promoted sides."),
    ("mbeumo", "MUN"): (0.85, 8, "Bryan Mbeumo (Man Utd MID, PS8.0, 13.5% owned) — explicitly fit and playing in pre-season (in the Rosenborg squad, 24 Jul), no tournament load, United's penalty #2. Rides the same HUL(A)2 + IPS(H)2 opening as Bruno at two-thirds of the price."),
    ("cunha", "MUN"): (0.78, 8, "Matheus Cunha (Man Utd MID, PS8.0, 14.9% owned) — in the confirmed low-risk group, fit through pre-season. Held slightly below Mbeumo because Carrick's front-line rotation between Cunha, Mbeumo, Sesko and Zirkzee is not fully settled, and Sesko's late ramp-up may actually free minutes here."),
    ("joao pedro", "CHE"): (0.78, 8, "Joao Pedro (Chelsea FWD, PS7.5, 47.2% owned) — in the confirmed low-World-Cup-risk group and therefore one of the few TEMPLATE picks that survives this overlay intact. Chelsea's new manager (Alonso) is the residual risk, plus genuine competition from Emegha (hamstring, out) and Estevao."),
    ("thiago", "BRE"): (0.8, 8, "Igor Thiago (Brentford FWD, PS8.0, 17.7% owned) — Brazil exited in the round of 16 (4-7 Jul), so ~24-26 days of build-up: effectively a normal pre-season. Brentford's nailed No.9 and penalty #1 under a returning manager (Andrews), so the priors hold. Brentford's opening four (TOT away, LEE away, SUN home, BOU away) is mid-table difficulty at worst."),
    ("brobbey", "SUN"): (0.78, 8, "Brian Brobbey (Sunderland FWD, PS6.0, 21.3% owned) — Netherlands exited at the round of 32, confirmed low-risk and rested. Sunderland's opening pair is IPS away (FDR2) then FUL home (FDR2), one of the softest starts in the league, under a returning manager (Le Bris)."),
    ("schade", "BRE"): (0.72, 8, "Kevin Schade (Brentford MID, PS6.0, 2.3% owned) — Germany exited at the round of 32, so fully rested. Our model rates him a top-20 asset on last season's rates at PS6.0; the 0.72 reflects genuine rotation in Brentford's front line rather than any fitness concern. A low-ownership value candidate, not a certainty."),
    ("n.williams", "NFO"): (0.75, 8, "Neco Williams (Forest DEF, PS5.0, 12.0% owned) — Wales did not qualify, and he STARTED Glasner's first friendly. Glasner's 3-4-2-1 creates genuine wing-back upside at Forest. Held at 0.75 rather than higher purely because the new-manager system change makes every Forest prior soft."),
    ("kayode", "BRE"): (0.7, 8, "Michael Kayode (Brentford DEF, PS4.5, 5.2% owned) — no tournament load, returning manager. A PS4.5 defender at a club whose priors we still trust; 0.7 reflects ordinary squad competition rather than any specific doubt."),
    ("shaw", "MUN"): (0.72, 8, "Luke Shaw (Man Utd DEF, PS4.5, 18.1% owned) — not in any World Cup cohort and STARTED the Rosenborg friendly (24 Jul), so fit and involved under Carrick. Held at 0.72 for his long-standing durability record rather than any current flag. Rides the HUL(A)2 + IPS(H)2 opening at PS4.5."),

    # ---------- SYSTEM READS: new managers create minutes the priors cannot see ----------
    ("kerkez", "LIV"): (0.78, 8, "Milos Kerkez (Liverpool DEF, PS5.5, 6.6% owned) — the team leg calls Iraola's full-backs the biggest system-driven mispricing in the game, and Kerkez is the cleanest expression of it. Iraola's Bournemouth full-backs were the most ADVANCED in the league; he now inherits a Liverpool side that (a) has the best GW1-8 fixture run in the league and (b) is the least World-Cup-damaged big club. Kerkez himself had no tournament (Hungary did not qualify), so he arrives with a full pre-season. Three independent edges stacking on a PS5.5 defender owned by 6.6%."),
    ("frimpong", "LIV"): (0.7, 8, "Jeremy Frimpong (Liverpool DEF, PS5.5, 3.0% owned) — same Iraola attacking-full-back thesis as Kerkez, on the right, at 3.0% ownership. Additionally, his direct competition is GONE: Conor Bradley is 'months away' per Iraola and Liverpool's other defensive injuries (Leoni ACL) thin the group further. Held at 0.70 rather than Kerkez's 0.78 only because Frimpong's own durability record is patchier and Iraola has not yet named a first-choice right-back."),
    ("virgil", "LIV"): (0.85, 8, "Virgil van Dijk (Liverpool DEF, PS6.5, 15.3% owned) — Netherlands exited at the round of 32, so fully rested and confirmed in the low-risk group. Captain and undroppable centre-back on the league's best fixture run. The most reliable minutes in our entire defensive shortlist."),
    ("a.becker", "LIV"): (0.8, 8, "Alisson Becker (Liverpool GKP, PS5.5, 4.5% owned) — Brazil exited in the round of 16, so a normal build-up. Liverpool's best fixture run plus a settled No.1. The residual is his own injury record, which is why this is 0.80 and not 0.88."),
    ("aina", "NFO"): (0.72, 8, "Ola Aina (Forest DEF, PS4.5, 4.6% owned) — Glasner's 3-4-2-1 is the system that turned Munoz and Mitchell into premium FPL assets at Palace, and Aina is the natural right wing-back inheriting it at PS4.5. No tournament load. Held at 0.72 because Glasner is brand new at Forest and every Forest prior is soft until we see a competitive XI."),
    ("robertson", "TOT"): (0.55, 8, "Andrew Robertson (Spurs DEF, PS4.5, 1.8% owned) — De Zerbi's 3-4-3 makes left wing-back a genuinely attacking role, and at PS4.5 with 1.8% ownership the asymmetry is attractive. Held at 0.55: he is 32, made only 11 starts last season, moved clubs this summer (so his prior start share is doubly unreliable), and competes with Spence for the slot. A watch, not a buy, until a competitive XI is seen."),
    ("mitchell", "CRY"): (0.72, 8, "Tyrick Mitchell (Palace DEF, PS4.5, 7.4% owned) — 3,253 minutes last season at 30.0 pts per PSm, one of the best value-per-million defenders in the game, and no tournament. Discounted to 0.72 rather than higher because Palace have a NEW and unproven manager (Pierre Sage) whose system is not yet known — the same caution applied to every new-manager club."),

    # ---------- PROMOTED-CLUB ENABLERS: research-derived; the model is ~95% blind here ----------
    ("van ewijk", "COV"): (0.8, 8, "Milan van Ewijk (Coventry DEF, PS4.0, 16.7% owned) — the consensus #1 cheap enabler and, unusually for a promoted-club pick, a well-evidenced one: 43 starts with 8 assists in the promotion season, no competition for the right-back slot, and he started Coventry's 18 Jul friendly. Our model is 93% blind on Coventry, so this number comes entirely from research. Coventry's GW1 is Arsenal away (FDR5), so he is a bench/enabler piece for GW1, not a starter."),
    ("thomas", "COV"): (0.75, 8, "Bobby Thomas (Coventry DEF, PS4.0, 5.0% owned) — 8.56 defensive contributions per 90, three goals, anchor of the best defence among the promoted sides, and he STARTED at centre-back in the 18 Jul friendly (0-0 v Northampton). DefCon points make a PS4.0 centre-back with that rate genuinely playable rather than merely cheap."),
    ("o'shea", "IPS"): (0.8, 8, "Dara O'Shea (Ipswich DEF, PS4.0, 1.2% owned) — played EVERY MINUTE of Ipswich's promotion season as captain and centre of the back three under a manager (Gary O'Neil) expected to keep a back five. The team leg rates him more nailed than Diop, who is 21.4% owned at the same price on 812 prior minutes. If that read is right this is a 20-point ownership swing available for free, and it is exactly the kind of gap our 96%-blind Ipswich model would never surface."),
    ("egan", "HUL"): (0.68, 8, "John Egan (Hull DEF, PS4.0, 0.9% owned) — roughly 13 defensive contributions per 90, the highest DefCon rate available at PS4.0. Held at 0.68: he is a 33-year-old with an injury history at the weakest of the three promoted sides, so the minutes are likelier than the clean sheets."),

    # ---------- BRIGHTON: the only club with August European football ----------
    ("verbruggen", "BHA"): (0.7, 2, "Bart Verbruggen (Brighton GKP, PS4.5, 16.1% owned) — Brighton are the ONLY Premier League club with European football in August (a UECL play-off across 20 and 27 Aug, which has already pushed their GW1 fixture to Sunday). That is a two-legged tie bracketing GW1 and GW2 and a rotation risk nobody is pricing on a 16%-owned budget keeper. Keepers rotate least, hence 0.70 rather than a harder fade, and duration 2 because the tie is over by GW3."),
    ("f.kadıoglu", "BHA"): (0.55, 2, "Ferdi Kadioglu (Brighton DEF, PS4.5, 2.9% owned) — same August UECL play-off (20 and 27 Aug) bracketing GW1-2, and outfield players rotate far more than keepers around a two-legged European tie. Duration 2."),
    ("gomez", "BHA"): (0.5, 2, "Carlos Baleba/Gomez slot (Brighton MID, PS5.0, 2.0% owned) — Brighton's August UECL play-off rotation applies, and he was a marginal pick to begin with. Duration 2."),

    # ---------- THE MODEL ARTIFACT THE OVERLAY EXISTS TO KILL ----------
    ("dubravka", "TOT"): (0.45, 8, "Martin Dubravka (Spurs GKP, PS4.0, 24.5% owned) — the single worst artifact in our projections table, and the reason this overlay file exists. He ranks #1 in the ENTIRE GAME by xPts per PSm because the model carried 35 starts he made for NEWCASTLE into a Tottenham shirt he joined on 1 July. He is 37, and Spurs are carrying three keepers (Vicario PS4.5, Kinsky PS4.5, Dubravka PS4.0). The genuinely uncertain part, and why this is 0.45 rather than a ban: Vicario missed the pre-season tour with an unflagged 'minor injury', which is presumably why 24.5% of the game has guessed Dubravka. It IS a guess — 39.3% of the game's goalkeeper exposure rides on an unresolved three-way battle. Flagged as a T-48h re-check; we do not pay for a coin flip when Raya and Alisson are knowable."),

    # ---------- HARD BANS: written here so the reasoning survives with the number ----------
    ("lacroix", "CRY"): (0.15, 8, "Maxence Lacroix (Palace DEF, PS6.0, 12.9% owned) — BAN. Two independent reasons: (1) Chelsea have AGREED a ~PS52m fee, personal terms are settled and a medical is booked, so 12.9% of the game is holding an asset about to be repriced and relisted under a different club; (2) he is a France third-place play-off returner in the deepest-fatigue cohort anyway. Either alone would be a fade; together they are a ban. Source: transfers.md sec 3.1."),
    ("kudus", "TOT"): (0.1, 8, "Mohammed Kudus (Spurs MID, PS6.5) — BAN. FPL shows a benign-looking 'd, 75% chance', but he has NOT trained with the group since a January quad injury, suffered a setback in April, and was omitted from the pre-season tour entirely; he is on a separate rehab track. The 75% flag is the most misleading number in the dataset after Garner's."),
    ("garner", "EVE"): (0.05, 8, "James Garner (Everton MID, PS6.0) — BAN. FPL says 'Expected back 22 Aug', which is GW1 matchday itself and reads as benign. He actually had SURGERY, and Everton's stated target is him returning to FIRST-TEAM TRAINING around that date, not playing. Described by the fitness leg as the most dangerous string in the dataset; he will not play GW1."),
    ("sesko", "MUN"): (0.3, 8, "Benjamin Sesko (Man Utd FWD, PS7.0) — AVOID for GW1. No competitive minutes since a shin injury in early May, and he missed BOTH pre-season friendlies (Wrexham 18 Jul, Rosenborg 24 Jul), staying in the UK rather than travelling. United are deliberately ramping him late. The 75% flag overstates his GW1 readiness."),
    ("j.timber", "ARS"): (0.15, 8, "Jurrien Timber (Arsenal DEF, PS6.5) — AVOID. FPL's 'expected back 21 Aug' is boilerplate, not a club statement: the groin problem dates to March, there is no confirmed timeline, and he is behind Ben White in the return queue."),
}

resolved, missing = {}, []
for (name, club), (share, dur, reason) in OVERLAYS.items():
    hits = by_name.get((name, club))
    if not hits:
        missing.append(f"{name} ({club})")
        continue
    if len(hits) > 1:
        missing.append(f"AMBIGUOUS {name} ({club}) -> {len(hits)} matches")
        continue
    e = hits[0]
    resolved[e["id"]] = {
        "start_share": share,
        "duration_gws": dur,
        "reason": reason,
        "_player": f"{e['web_name']} ({club}, {e['now_cost']/10:.1f})",
    }

out = ROOT / "decisions" / "overlays" / "gw01.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(resolved, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"resolved {len(resolved)} overlays -> {out}")
if missing:
    print("UNRESOLVED:")
    for m in missing:
        print("  ", m)
